name: format_and_commit

on:
  pull_request:
    branches: [main]
jobs:
  formatter:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Checktest
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get last commit author name
        run: |
          echo "LAST_COMMITTER_NAME=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
      
      - name: Check if it is necessary
        run: |
          echo $LAST_COMMITTER_NAME
          echo [[ $LAST_COMMITER_NAME == 'GitHub Action' ]]
          echo [[ $LAST_COMMITER_NAME == GitHub Action ]]
          if [[ $LAST_COMMIT_AUTHOR_NAME == GitHub Action]] ; then
            echo "Last commiter is Github_Action."
            exit 1
          else
            echo "Committed by user"
          fi

      - name: Create directory
        run: mkdir -p Hutzper.Library.FormsMekiki/bin/x64/

      - name: Write commit hash
        run: echo "${SHA::6}" > Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt

      - name: Auto-commit if changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Apply CommitHash.txt"
          git push