name: Generate CommitHash.txt

on:
  push:

jobs:
  generate_commit_hash:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha:0:6 }}
    steps:
      - run: echo "$SHA" >> CommitHash.txt