name: Generate CommitHash.txt

on:
  pull_request:
    branches: [main]

jobs:
  generate_commit_hash:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      # 安全な directory であると明記
      - name: safe dirctory
        run: git config --global --add safe.directory $(pwd)

      - name: Create directory
        run: mkdir -p Hutzper.Library.FormsMekiki/bin/x64/

      - name: Write commit hash
        run: echo "${SHA::6}" > Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt

      - name: Get current branch name
        id: branch_name
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: commit push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config advice.addIgnoredFile false
          git add -f Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt
          git commit -m "Add short commit hash"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}