name: Generate CommitHash.txt

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  generate_commit_hash:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Write commit hash
        run: echo "${SHA::6}" > test/test/CommitHash.txt