name: Generate CommitHash.txt

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  generate_commit_hash:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      # push 用の token を取得
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      # 安全な directory であると明記
      - name: safe dirctory
        run: git config --global --add safe.directory $(pwd)

      - name: Create directory
        run: mkdir -p Hutzper.Library.FormsMekiki/x64/

      - name: Write commit hash
        run: echo "${SHA::6}" > Hutzper.Library.FormsMekiki/x64/CommitHash.txt

      - name: commit push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add test/test/CommitHash.txt
          git commit -m "Add short commit hash"
          git push
