name: Generate CommitHash.txt

on:
  pull_request:
    branches: 
      - main
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**/CommitHash.txt"

jobs:
  generate_commit_hash:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Check Actor
        run: echo ${{ github.actor }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Check if directory exists
        run: |
          if [ -d "Hutzper.Library.FormsMekiki/bin/x64/" ]; then
            echo "Directory already exists, skipping creation"
            exit 0
          else
            echo "Directory does not exist, creating..."
          fi
      
      - name: Create directory
        run: mkdir -p Hutzper.Library.FormsMekiki/bin/x64/

      - name: Write commit hash
        run: echo "${SHA::6}" > Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt

      - name: commit push
        run: |
          git config user.name github-actions
          git config user.email action@github.com
          git config advice.addIgnoredFile false
          git add -f Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt
          git commit -m "Add short commit hash"
          git push origin HEAD:${{ github.head_ref }} --force
