name: Generate CommitHash.txt

on:
  pull_request:
    branches: [main]
    types: [closed]  

jobs:
  generate_commit_hash:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Create directory
        run: mkdir -p Hutzper.Library.FormsMekiki/bin/x64/

      - name: Write commit hash
        run: echo "${SHA::6}" > Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt

      - name: commit push
        run: |
          git config user.name github-actions
          git config user.email action@github.com
          git config advice.addIgnoredFile false
          git add -f Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt
          git commit -m "Add short commit hash"
          git push origin HEAD:${{ github.head_ref }} --force