name: Generate CommitHash.txt

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - "**/CommitHash.txt"

jobs:
  generate_commit_hash:
    if: github.actor != 'github-actions' && github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "CommitHash.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
      
      - name: Create directory
        run: mkdir -p Hutzper.Library.FormsMekiki/bin/x64/

      - name: Write commit hash
        run: echo "${SHA::6}" > Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt

      - name: commit push
        run: |
          git config user.name github-actions
          git config user.email action@github.com
          git config advice.addIgnoredFile false
          git add -f Hutzper.Library.FormsMekiki/bin/x64/CommitHash.txt
          git commit -m "Add short commit hash"
          git push origin HEAD:${{ github.head_ref }} --force