name: format_and_commit

on:
  pull_request:
    types: [closed]
permissions: write-all
jobs:
  formatter:
    runs-on: windows-latest
    steps:
      - name: Checktest
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format
      - name: Format code
        run: dotnet format
      - name: Auto-commit if changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Apply Code Formatter Change"
          git push